/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zsteel;

import java.awt.Color;

/**
 *
 * @author mahmoud
 */
public class D_finaninside extends javax.swing.JDialog {

    
    public D_finaninside(f_financial parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public D_finaninside()
    {initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpgroub = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jlexit = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jpBut_supllier2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jpBut_supllier3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jpBut_supllier4 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jpBut_supllier5 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jpBut_supllier6 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jpgroub.setBackground(new java.awt.Color(255, 255, 255));
        jpgroub.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlexit.setBackground(new java.awt.Color(0, 51, 255));
        jlexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Delete_32px.png"))); // NOI18N
        jlexit.setOpaque(true);
        jlexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlexitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlexitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlexitMouseExited(evt);
            }
        });
        jPanel2.add(jlexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("اختر نوع العمليه");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 90, 30));

        jpgroub.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 30));

        jpBut_supllier2.setBackground(new java.awt.Color(255, 255, 255));
        jpBut_supllier2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jpBut_supllier2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpBut_supllier2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpBut_supllier2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpBut_supllier2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpBut_supllier2MousePressed(evt);
            }
        });
        jpBut_supllier2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Renew Subscription_64px.png"))); // NOI18N
        jLabel15.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jpBut_supllier2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 60, 70));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("فاتوره مرتجع لمورد");
        jLabel16.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jpBut_supllier2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 120, -1));

        jpgroub.add(jpBut_supllier2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 120, 90));

        jpBut_supllier3.setBackground(new java.awt.Color(255, 255, 255));
        jpBut_supllier3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jpBut_supllier3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpBut_supllier3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpBut_supllier3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpBut_supllier3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpBut_supllier3MousePressed(evt);
            }
        });
        jpBut_supllier3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Money Bag Euro_64px.png"))); // NOI18N
        jLabel17.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jpBut_supllier3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 60, 60));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("ايداع نقدى للخزنه");
        jLabel18.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jpBut_supllier3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jpgroub.add(jpBut_supllier3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 120, 90));

        jpBut_supllier4.setBackground(new java.awt.Color(255, 255, 255));
        jpBut_supllier4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jpBut_supllier4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpBut_supllier4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpBut_supllier4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpBut_supllier4MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpBut_supllier4MousePressed(evt);
            }
        });
        jpBut_supllier4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Paycheque_64px.png"))); // NOI18N
        jLabel19.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jpBut_supllier4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 60, 60));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("فاتوره بيع");
        jLabel20.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jpBut_supllier4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 100, -1));

        jpgroub.add(jpBut_supllier4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 120, 90));

        jpBut_supllier5.setBackground(new java.awt.Color(255, 255, 255));
        jpBut_supllier5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jpBut_supllier5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpBut_supllier5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpBut_supllier5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpBut_supllier5MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpBut_supllier5MousePressed(evt);
            }
        });
        jpBut_supllier5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/supplier_50px.png"))); // NOI18N
        jLabel21.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jpBut_supllier5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 60, 50));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("خصم لمورد");
        jLabel22.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jpBut_supllier5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 90, -1));

        jpgroub.add(jpBut_supllier5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 120, 90));

        jpBut_supllier6.setBackground(new java.awt.Color(255, 255, 255));
        jpBut_supllier6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jpBut_supllier6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpBut_supllier6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpBut_supllier6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpBut_supllier6MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpBut_supllier6MousePressed(evt);
            }
        });
        jpBut_supllier6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Initiate Money Transfer_64px.png"))); // NOI18N
        jLabel23.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jpBut_supllier6.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 60, 60));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("خصم لعميل");
        jLabel24.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jpBut_supllier6.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 90, -1));

        jpgroub.add(jpBut_supllier6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 120, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpgroub, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpgroub, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(486, 347));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jlexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlexitMouseClicked
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jlexitMouseClicked

    private void jlexitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlexitMouseEntered
        jlexit.setBackground(Color.CYAN);
        // TODO add your handling code here:
    }//GEN-LAST:event_jlexitMouseEntered

    private void jlexitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlexitMouseExited
        jlexit.setBackground(new java.awt.Color(0, 51, 255));

    }//GEN-LAST:event_jlexitMouseExited

    private void jpBut_supllier2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpBut_supllier2MouseClicked

        setVisible(false);
        new D_finaninside_billrecall(this, true).setVisible(true);
    }//GEN-LAST:event_jpBut_supllier2MouseClicked

    private void jpBut_supllier2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpBut_supllier2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jpBut_supllier2MouseEntered

    private void jpBut_supllier2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpBut_supllier2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jpBut_supllier2MouseExited

    private void jpBut_supllier2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpBut_supllier2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpBut_supllier2MousePressed

    private void jpBut_supllier3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpBut_supllier3MouseClicked
            setVisible(false);
            new D_finaninside_cashdeposit(this, true).setVisible(true);
                    
    }//GEN-LAST:event_jpBut_supllier3MouseClicked

    private void jpBut_supllier3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpBut_supllier3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jpBut_supllier3MouseEntered

    private void jpBut_supllier3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpBut_supllier3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jpBut_supllier3MouseExited

    private void jpBut_supllier3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpBut_supllier3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpBut_supllier3MousePressed

    private void jpBut_supllier4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpBut_supllier4MouseClicked
        
        setVisible(false);
        new D_finaninside_sale(this, true).setVisible(true);
    }//GEN-LAST:event_jpBut_supllier4MouseClicked

    private void jpBut_supllier4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpBut_supllier4MouseEntered
         // TODO add your handling code here:
    }//GEN-LAST:event_jpBut_supllier4MouseEntered

    private void jpBut_supllier4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpBut_supllier4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jpBut_supllier4MouseExited

    private void jpBut_supllier4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpBut_supllier4MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpBut_supllier4MousePressed

    private void jpBut_supllier5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpBut_supllier5MouseClicked
new D_finaninside_suppdiscount(this, true).setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_jpBut_supllier5MouseClicked

    private void jpBut_supllier5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpBut_supllier5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jpBut_supllier5MouseEntered

    private void jpBut_supllier5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpBut_supllier5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jpBut_supllier5MouseExited

    private void jpBut_supllier5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpBut_supllier5MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpBut_supllier5MousePressed

    private void jpBut_supllier6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpBut_supllier6MouseClicked

        setVisible(false);
        new D_finaninside_cashdepositcustmor(this, true).setVisible(true);
        
    }//GEN-LAST:event_jpBut_supllier6MouseClicked

    private void jpBut_supllier6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpBut_supllier6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jpBut_supllier6MouseEntered

    private void jpBut_supllier6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpBut_supllier6MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jpBut_supllier6MouseExited

    private void jpBut_supllier6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpBut_supllier6MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpBut_supllier6MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(D_finaninside.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(D_finaninside.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(D_finaninside.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(D_finaninside.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                D_finaninside dialog = new D_finaninside(new f_financial(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jlexit;
    private javax.swing.JPanel jpBut_supllier2;
    private javax.swing.JPanel jpBut_supllier3;
    private javax.swing.JPanel jpBut_supllier4;
    private javax.swing.JPanel jpBut_supllier5;
    private javax.swing.JPanel jpBut_supllier6;
    private javax.swing.JPanel jpgroub;
    // End of variables declaration//GEN-END:variables
}
