/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zsteel;

import java.awt.Color;


public class D_finanmanger extends javax.swing.JDialog {
   

    
    public D_finanmanger(f_financial parent, boolean model) {
        super(parent,model);
        initComponents();
    }
public D_finanmanger()
{
        initComponents();
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jlexit = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlmanager = new javax.swing.JList<>();
        jbdelete = new javax.swing.JButton();
        jbadd = new javax.swing.JButton();
        jbupdata = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlexit.setBackground(new java.awt.Color(0, 51, 255));
        jlexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Delete_32px.png"))); // NOI18N
        jlexit.setOpaque(true);
        jlexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlexitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlexitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlexitMouseExited(evt);
            }
        });
        jPanel2.add(jlexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("المديرين ومسئولى الماليات");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 170, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 30));

        jlmanager.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jlmanager);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 270, 330));

        jbdelete.setBackground(new java.awt.Color(255, 51, 0));
        jbdelete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbdelete.setForeground(new java.awt.Color(255, 255, 255));
        jbdelete.setText("حذف");
        jbdelete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jbdelete.setContentAreaFilled(false);
        jbdelete.setOpaque(true);
        jbdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbdeleteActionPerformed(evt);
            }
        });
        jPanel1.add(jbdelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 60, 20));

        jbadd.setBackground(new java.awt.Color(0, 102, 204));
        jbadd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbadd.setForeground(new java.awt.Color(255, 255, 255));
        jbadd.setText("اضافه جديد");
        jbadd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jbadd.setContentAreaFilled(false);
        jbadd.setOpaque(true);
        jbadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbaddActionPerformed(evt);
            }
        });
        jPanel1.add(jbadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 100, 20));

        jbupdata.setBackground(new java.awt.Color(0, 204, 255));
        jbupdata.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbupdata.setForeground(new java.awt.Color(255, 255, 255));
        jbupdata.setText("تعديل");
        jbupdata.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jbupdata.setContentAreaFilled(false);
        jbupdata.setOpaque(true);
        jbupdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbupdataActionPerformed(evt);
            }
        });
        jPanel1.add(jbupdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 60, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 490));

        setSize(new java.awt.Dimension(350, 429));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jlexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlexitMouseClicked
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jlexitMouseClicked

    private void jlexitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlexitMouseEntered
        jlexit.setBackground(Color.CYAN);
        // TODO add your handling code here:
    }//GEN-LAST:event_jlexitMouseEntered

    private void jlexitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlexitMouseExited
        jlexit.setBackground(new java.awt.Color(0, 51, 255));

        
    }//GEN-LAST:event_jlexitMouseExited

    private void jbaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbaddActionPerformed
      
       
       
     new    D_finanadd(this, true).setVisible(true);
      
        
        
    }//GEN-LAST:event_jbaddActionPerformed

    private void jbupdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbupdataActionPerformed

            new D_finanupdata(this, true).setVisible(true);
    }//GEN-LAST:event_jbupdataActionPerformed

    private void jbdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbdeleteActionPerformed

            new D_finandelete(this, true).setVisible(true);
    }//GEN-LAST:event_jbdeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(D_finanmanger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(D_finanmanger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(D_finanmanger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(D_finanmanger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                D_finanmanger dialog = new D_finanmanger(new f_financial(),true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbadd;
    private javax.swing.JButton jbdelete;
    private javax.swing.JButton jbupdata;
    private javax.swing.JLabel jlexit;
    private javax.swing.JList<String> jlmanager;
    // End of variables declaration//GEN-END:variables
}
