/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zsteel;

/**
 *
 * @author mahmoud
 */
public class D_finanaddout_data extends java.awt.Dialog {

    
    /**
     * Creates new form D_addclient
     * @param parent
     * @param model
     */
     public D_finanaddout_data(D_finaninside_cashdepositcustmor parent,boolean model) {
        super(parent);
        initComponents();
    }
    public D_finanaddout_data(D_finaninside_cashdeposit parent,boolean model) {
        super(parent);
        initComponents();
    }
     public D_finanaddout_data(D_finaninside_suppdiscount parent,boolean model) {
        super(parent);
        initComponents();
    }
    public D_finanaddout_data(D_finaninside_billrecall parent,boolean model) {
        super(parent);
        initComponents();
    }
     public D_finanaddout_data(D_finaninside_sale parent,boolean model) {
        super(parent);
        initComponents();
    }
    public D_finanaddout_data(D_finanaaddout_custorecall parent,boolean model) {
        super(parent);
        initComponents();
    }
     public D_finanaddout_data(D_finanaaddout_custodiscount parent,boolean model) {
        super(parent);
        initComponents();
    }
    public D_finanaddout_data(D_finanaaddout_receipt parent,boolean model) {
        super(parent);
        initComponents();
    }
     public D_finanaddout_data(D_finanaaddout_receiptcust parent,boolean model) {
        super(parent);
        initComponents();
    }
     public D_finanaddout_data(D_finanaaddout_closemoney parent ,boolean model) {
        super(parent);
        initComponents();
    }
     public D_finanaddout_data(D_finanaaddout_mangamentmony parent,boolean model) {
        super(parent);
        initComponents();
    }
      public D_finanaddout_data(D_finanaaddout_supppayments parent,boolean model) {
        super(parent);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooser1 = new cambodia.raven.DateChooser();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jpdata = new javax.swing.JPanel();
        jtfdata = new javax.swing.JTextField();
        jbdata = new javax.swing.JButton();

        dateChooser1.setButton(jbdata);
        dateChooser1.setTextRefernce(jtfdata);

        setBounds(new java.awt.Rectangle(450, 200, 400, 300));
        setModal(true);
        setUndecorated(true);
        setSize(new java.awt.Dimension(300, 400));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(250, 250, 250));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("اختر تاريخ");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 30));

        jButton1.setBackground(new java.awt.Color(255, 0, 51));
        jButton1.setText("الغاء");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setOpaque(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 63, 26));

        jButton2.setBackground(new java.awt.Color(204, 204, 255));
        jButton2.setText("تاكيد");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setOpaque(true);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 63, 26));

        jpdata.setAutoscrolls(true);
        jpdata.setOpaque(false);
        jpdata.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtfdata.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        jpdata.add(jtfdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 30));

        jbdata.setBorder(null);
        jbdata.setContentAreaFilled(false);
        jpdata.add(jbdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 30, 30));

        jPanel2.add(jpdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 200, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
       
    }//GEN-LAST:event_closeDialog

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          setVisible(false);  
        D_finanaaddout_receipt find = new D_finanaaddout_receipt();
        D_finaninside_sale d = new D_finaninside_sale();
        d.a =false;
            find.jldata.setText(dateChooser1.getSelectedDate());
      
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
               
                D_finanaddout_data dialog;
                dialog =  new D_finanaddout_data(new D_finanaaddout_receipt(),true);
                dialog = new D_finanaddout_data(new D_finaninside_cashdeposit(),true);
                

                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public cambodia.raven.DateChooser dateChooser1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbdata;
    private javax.swing.JPanel jpdata;
    private javax.swing.JTextField jtfdata;
    // End of variables declaration//GEN-END:variables
}
