
package zsteel;

import UI.scrollbar;
import UI.tableheader;
import java.awt.Color;
import java.awt.ComponentOrientation;
import java.awt.Dimension;
import java.awt.Panel;
import javax.swing.JScrollPane;


import static javax.swing.SwingConstants.RIGHT;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author mahmoud
 */
public class D_finaninside_sale extends javax.swing.JDialog {
       public boolean a;
    DefaultTableModel m;
    public D_finaninside_sale(D_finaninside parent, boolean modal) {
        super(parent, modal);
        initComponents();
        dtable();
    }
    public D_finaninside_sale(D_managaddbill parent, boolean modal) {
        super(parent, modal);
        initComponents();
        dtable();
    }
public D_finaninside_sale()
{
  initComponents();
        dtable();   
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpaddsupp = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jbadd = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrolltable = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jpdata = new javax.swing.JPanel();
        jpadddata = new javax.swing.JPanel();
        jlcach = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jpdata1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jldata = new javax.swing.JLabel();
        jpdata2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jlgetsuppl = new javax.swing.JLabel();
        jpdata3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jpadddata3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("كشف حساب عميل");
        setAlwaysOnTop(true);
        setIconImage(null);
        setIconImages(null);
        setModal(true);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpaddsupp.setBackground(new java.awt.Color(255, 255, 255));
        jpaddsupp.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.darkGray, null));
        jpaddsupp.setAutoscrolls(true);
        jpaddsupp.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jpaddsupp.setFocusCycleRoot(true);
        jpaddsupp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField2.setBorder(null);
        jpaddsupp.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 340, 20));

        jbadd.setBackground(new java.awt.Color(0, 212, 149));
        jbadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Plus Math_32px.png"))); // NOI18N
        jbadd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jbadd.setBorderPainted(false);
        jbadd.setContentAreaFilled(false);
        jbadd.setOpaque(true);
        jbadd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbaddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbaddMouseExited(evt);
            }
        });
        jbadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbaddActionPerformed(evt);
            }
        });
        jpaddsupp.add(jbadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Search.png"))); // NOI18N
        jpaddsupp.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, -1, 40));

        jPanel1.add(jpaddsupp, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 410, 40));

        jPanel2.setBackground(new java.awt.Color(0, 102, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 51, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Delete_32px.png"))); // NOI18N
        jLabel1.setOpaque(true);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("فاتوره بيع جديده");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 120, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 0, 850, 30));

        jScrolltable.getVerticalScrollBar().setUI(new scrollbar());
        jScrolltable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrolltable.setHorizontalScrollBarPolicy(31);
        jScrolltable.setAutoscrolls(true);
        jScrolltable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jScrolltableMouseEntered(evt);
            }
        });

        table.setAutoCreateRowSorter(true);
        table.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        table.setModel(new DefaultTableModel(new Object[0][], new String []{"مسلسل","التاريخ","نوع العمليه","بيان","الكميه","السعر","دائن","مدين","الرصيد"}));
        table.setRowHeight(30);
        table.setSurrendersFocusOnKeystroke(true);
        jScrolltable.setViewportView(table);

        jPanel1.add(jScrolltable, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 800, 480));

        jpdata.setBackground(new java.awt.Color(0, 0, 0));
        jpdata.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpadddata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpadddataMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpadddataMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpadddataMouseExited(evt);
            }
        });

        jlcach.setBackground(new java.awt.Color(153, 153, 255));
        jlcach.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlcach.setText("مدفوع كاش");
        jlcach.setOpaque(true);
        jlcach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlcachMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlcachMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlcachMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jpadddataLayout = new javax.swing.GroupLayout(jpadddata);
        jpadddata.setLayout(jpadddataLayout);
        jpadddataLayout.setHorizontalGroup(
            jpadddataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpadddataLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlcach, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpadddataLayout.setVerticalGroup(
            jpadddataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlcach, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
        );

        jpdata.add(jpadddata, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 20));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("نوع الدفع");
        jpdata.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 60, 20));

        jPanel1.add(jpdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 130, 20));

        jpdata1.setBackground(new java.awt.Color(0, 0, 0));
        jpdata1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("التاريخ");
        jpdata1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 40, 20));

        jldata.setBackground(new java.awt.Color(102, 153, 255));
        jldata.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jldata.setForeground(new java.awt.Color(255, 255, 255));
        jldata.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jldata.setOpaque(true);
        jldata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jldataMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jldataMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jldataMouseExited(evt);
            }
        });
        jpdata1.add(jldata, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 20));

        jPanel1.add(jpdata1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 40, 180, 20));

        jpdata2.setBackground(new java.awt.Color(0, 0, 0));
        jpdata2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("العميل");
        jpdata2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 40, 20));

        jlgetsuppl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlgetsuppl.setOpaque(true);
        jlgetsuppl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlgetsupplMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlgetsupplMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlgetsupplMouseExited(evt);
            }
        });
        jpdata2.add(jlgetsuppl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 20));

        jPanel1.add(jpdata2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 200, 20));

        jpdata3.setBackground(new java.awt.Color(0, 0, 0));
        jpdata3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("رقم الفاتوره");
        jpdata3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 60, 20));

        jTextField1.setBackground(new java.awt.Color(204, 204, 204));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.setBorder(null);
        jpdata3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 20));

        jPanel1.add(jpdata3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 180, 20));

        jpadddata3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpadddata3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpadddata3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpadddata3MouseExited(evt);
            }
        });
        jpadddata3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ملاحظات");
        jLabel8.setAutoscrolls(true);
        jLabel8.setDoubleBuffered(true);
        jLabel8.setFocusTraversalPolicyProvider(true);
        jLabel8.setOpaque(true);
        jpadddata3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 50, 50));
        jLabel8.getAccessibleContext().setAccessibleDescription("");

        jTextArea1.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea1.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("لايوجد\n");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setBorder(null);
        jpadddata3.add(jTextArea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 50));

        jPanel1.add(jpadddata3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 340, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(853, 768));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
            jLabel1.setBackground(Color.CYAN);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
                    jLabel1.setBackground(new java.awt.Color(0, 51, 255));

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseExited

    private void jScrolltableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrolltableMouseEntered
        jScrolltable.getVerticalScrollBar().setForeground(Color.red);
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrolltableMouseEntered

    private void jpadddataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpadddataMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jpadddataMouseClicked

    private void jpadddataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpadddataMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jpadddataMouseEntered

    private void jpadddataMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpadddataMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jpadddataMouseExited

    private void jpadddata3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpadddata3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jpadddata3MouseClicked

    private void jpadddata3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpadddata3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jpadddata3MouseEntered

    private void jpadddata3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpadddata3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jpadddata3MouseExited

    private void jbaddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbaddMouseEntered
                // TODO add your handling codeere:
                jbadd.setBackground(new Color(109,216,221));
    }//GEN-LAST:event_jbaddMouseEntered

    private void jldataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jldataMouseClicked
           a = true;
  new D_finanaddout_data(this,true).setVisible(a);
D_finanaddout_data d = new D_finanaddout_data(this,true);
//d.setVisible(true);

    if( a==false){ 
                jldata.setText(d.dateChooser1.getSelectedDate());

    }
    
    
    }//GEN-LAST:event_jldataMouseClicked

    private void jbaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbaddActionPerformed
            
       
    }//GEN-LAST:event_jbaddActionPerformed

    private void jlgetsupplMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlgetsupplMouseClicked
 new D_finaninside_sale_getcus(this, true).setVisible(true);

    }//GEN-LAST:event_jlgetsupplMouseClicked

    private void jlgetsupplMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlgetsupplMouseEntered
        // TODO add your handling code here:
        jlgetsuppl.setBackground(Color.orange);
    }//GEN-LAST:event_jlgetsupplMouseEntered

    private void jlgetsupplMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlgetsupplMouseExited
        // TODO add your handling code here:
        jlgetsuppl.setBackground(new Color(240,240,240));
    }//GEN-LAST:event_jlgetsupplMouseExited

    private void jbaddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbaddMouseExited
        jbadd.setBackground(new java.awt.Color(0, 212, 149));

        // TODO add your handling code here:
    }//GEN-LAST:event_jbaddMouseExited

    private void jlcachMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlcachMouseEntered
        // TODO add your handling code here:
                jlcach.setBackground(Color.orange);

    }//GEN-LAST:event_jlcachMouseEntered

    private void jlcachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlcachMouseClicked
               

        if(jlcach.getText().equals("مدفوع كاش"))
        {
            
            jlcach.setText("حساب جارى");
        }else if(jlcach.getText().equals("حساب جارى"))
        {
         jlcach.setText("مدفوع كاش");

        }
        if(jlcach.getText().equals("مدفوع كاش")){
                        jlcach.setBackground(new Color(153,153,255));

        }else if(jlcach.getText().equals("حساب جارى")){
                                    jlcach.setBackground(new Color(255,153,153));
        }
        
   
        
               
              
    }//GEN-LAST:event_jlcachMouseClicked

    private void jlcachMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlcachMouseExited
        // TODO add your handling code here:
         if(jlcach.getText().equals("مدفوع كاش")){
                        jlcach.setBackground(new Color(153,153,255));

        }else if(jlcach.getText().equals("حساب جارى")){
                                    jlcach.setBackground(new Color(255,153,153));
        }
    }//GEN-LAST:event_jlcachMouseExited

    private void jldataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jldataMouseEntered
       jldata.setBackground(Color.orange);
    }//GEN-LAST:event_jldataMouseEntered

    private void jldataMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jldataMouseExited
        // TODO add your handling code here:
                jldata.setBackground(new java.awt.Color(102, 153, 255));

    }//GEN-LAST:event_jldataMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(D_finaninside_sale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(D_finaninside_sale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(D_finaninside_sale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(D_finaninside_sale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                D_finaninside_sale dialog ;
                      dialog  = new D_finaninside_sale(new D_finaninside(), true);
                      dialog  = new D_finaninside_sale(new D_managaddbill(), true);
                
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

     public  void dtable ()
    {
        String [] columnx ={"مسلسل","التاريخ","نوع العمليه","بيان","الكميه","السعر","دائن","مدين","الرصيد"};
        D_finanaddout_data d = new D_finanaddout_data(this,true);
//d.setVisible(true);
        jldata.setText(d.dateChooser1.getSelectedDate());
       
       m = new DefaultTableModel(columnx,0)
       {
            Class[] types = { Integer.class, String.class, String.class, String.class, String.class, String.class };
        
            public boolean iscelleditable(int row , int column)
         {
             return true;
         }
        
         
       };
       table.setModel(m);
        
        
        
          
           
           
        
        table.setModel(m);
        Object []a={"1","سيليبليبل","sdf","sfd","fsd","fds","dfs"};       
        
        m.addRow(a);
      
        
      
    
     
        
          JTableHeader header = table.getTableHeader();
       header.setPreferredSize(new Dimension(0, 30));
       header.setEnabled(false);
       table.getTableHeader().setDefaultRenderer(new tableheader());
    table.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);

       
        jScrolltable.getViewport().setBackground(Color.white);
        Panel p =new Panel();
        p.setBackground(Color.BLACK);
        jScrolltable.setCorner("UPPER_RIGHT_CORNER", p);
        jScrolltable. setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        table.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        
        
   
        
        
        
        //start customize  size column range 60:200
        TableColumnModel column = table.getColumnModel();
        
       /* if(address){
        column.getColumn(0).setPreferredWidth(60);
        column.getColumn(0).setMaxWidth(60);
        column.getColumn(1).setPreferredWidth(100);
        column.getColumn(1).setMaxWidth(100);
        column.getColumn(2).setPreferredWidth(150);
        column.getColumn(2).setMaxWidth(150);
        column.getColumn(3).setPreferredWidth(150);
        column.getColumn(3).setMaxWidth(150);
        column.getColumn(4).setPreferredWidth(150);
        column.getColumn(4).setMaxWidth(150);
        column.getColumn(5).setPreferredWidth(150);
        column.getColumn(5).setMaxWidth(150);
        column.getColumn(6).setPreferredWidth(150);
        column.getColumn(6).setMaxWidth(150);
//        column.getColumn(7).setPreferredWidth(150);
  //      column.getColumn(7).setMaxWidth(150);
       // column.getColumn(8).setPreferredWidth(150);
       // column.getColumn(8).setMaxWidth(150);
        }
        else 
        {
            address= false;
            
        }
        table.setColumnModel(column);
        //end size column
        */
      
        table.setDefaultEditor(Object.class, null);
        
        //start customize row in table
       /* DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(0);
    table.getColumnModel().getColumn(0).setCellRenderer(rightRenderer);    
    table.getColumnModel().getColumn(1).setCellRenderer(rightRenderer);
    table.getColumnModel().getColumn(2).setCellRenderer(rightRenderer);
    table.getColumnModel().getColumn(3).setCellRenderer(rightRenderer);
    table.getColumnModel().getColumn(4).setCellRenderer(rightRenderer);
    table.getColumnModel().getColumn(5).setCellRenderer(rightRenderer);
    table.getColumnModel().getColumn(6).setCellRenderer(rightRenderer);
    table.getColumnModel().getColumn(7).setCellRenderer(rightRenderer);
    table.getColumnModel().getColumn(8).setCellRenderer(rightRenderer);
  // end customize row
  */
       DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
     
        
        
      
    
    renderer.setHorizontalAlignment(RIGHT);
    for (int i = 0; i < table.getColumnCount(); i++)
    {
      table.getColumn(table.getColumnName(i)).setCellRenderer(renderer);

    }
       
        
        table.setModel(m);
       
    }
    private void selectclient()
    {
   
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrolltable;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton jbadd;
    private javax.swing.JLabel jlcach;
    public javax.swing.JLabel jldata;
    private javax.swing.JLabel jlgetsuppl;
    private javax.swing.JPanel jpadddata;
    private javax.swing.JPanel jpadddata3;
    private javax.swing.JPanel jpaddsupp;
    private javax.swing.JPanel jpdata;
    private javax.swing.JPanel jpdata1;
    private javax.swing.JPanel jpdata2;
    private javax.swing.JPanel jpdata3;
    public javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
