/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zsteel;

import    UI.WaitLayerUI;
import java.awt.Color;
import java.awt.Dimension;

import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyListener;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLayer;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.KeyStroke;
import javax.swing.Timer;

/**
 *
 * @author mahmoud
 */


@SuppressWarnings("serial")
public class f_login extends javax.swing.JFrame implements ActionListener, KeyListener {
 boolean a =false;
 WaitLayerUI layerUI;
JLayer<JPanel> jlayer;
 Timer stopper;
    /**
     * Creates new form f_login
     */
    public f_login() {
        initComponents();
       
          layerUI = new WaitLayerUI();
    
  jlayer = new JLayer<JPanel>(jPanel2, layerUI);
    
   stopper = new Timer(4000, new ActionListener() {
      public void actionPerformed(ActionEvent ae) {
        layerUI.stop();
      }
    });
    stopper.setRepeats(false);

    
  
        jPanel1.add(jlayer);
     

      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jlb_name = new javax.swing.JLabel();
        jl_pass = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jtx_name = new javax.swing.JTextField();
        jtx_pass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jl_eror = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("zsteel");
        setBounds(new java.awt.Rectangle(400, 130, 20, 400));

        jPanel3.setLayout(new java.awt.CardLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ring.gif"))); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 160, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(121, 121, 121))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(209, Short.MAX_VALUE)
                .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 139, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(124, 124, 124))
        );

        jPanel3.add(jPanel2, "card3");

        setIconImage(new ImageIcon(getClass().getResource("/icon/steel1.png")).getImage());
        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 0, 51));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("تسجيل الدخول");
        jButton1.addActionListener(this);
        jButton1.addKeyListener(this);

        jtx_name.addActionListener(this);

        jLabel1.setText("اظهار كلمه السر");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(10, 10, 10)
                        .add(jlb_name, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 131, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(8, 8, 8)
                        .add(jtx_name, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 160, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(10, 10, 10)
                        .add(jl_pass, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 131, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(8, 8, 8)
                        .add(jtx_pass, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 160, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(196, 196, 196)
                        .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 86, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(159, 159, 159)
                        .add(jButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 132, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(159, 159, 159)
                        .add(jl_eror, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(143, 143, 143)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jlb_name, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jtx_name, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(47, 47, 47)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jl_pass, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 26, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jtx_pass, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(14, 14, 14)
                .add(jLabel1)
                .add(59, 59, 59)
                .add(jButton1)
                .add(40, 40, 40)
                .add(jl_eror, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel1, "card2");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(450, 511));
        setLocationRelativeTo(null);
    }

    // Code for dispatching events from components to event handlers.

    public void actionPerformed(java.awt.event.ActionEvent evt) {
        if (evt.getSource() == jButton1) {
            f_login.this.jButton1ActionPerformed(evt);
        }
        else if (evt.getSource() == jtx_name) {
            f_login.this.jtx_nameActionPerformed(evt);
        }
    }

    public void keyPressed(java.awt.event.KeyEvent evt) {
        if (evt.getSource() == jButton1) {
            f_login.this.jButton1KeyPressed(evt);
        }
    }

    public void keyReleased(java.awt.event.KeyEvent evt) {
    }

    public void keyTyped(java.awt.event.KeyEvent evt) {
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
arror_login();
         jPanel2.validate();
        jPanel1.hide();
        try {
            test_login();
            if(a==false){
                return;
            }
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(f_login.class.getName()).log(Level.SEVERE, null, ex);
           
                
        }
       
         layerUI.start();
          if (!stopper.isRunning()) {
            stopper.start();
          }
         setVisible(false); 
     new f_main().setVisible(true);
     
    
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtx_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtx_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtx_nameActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
                jButton1.getInputMap().put(KeyStroke.getKeyStroke("enter"),"jButton1");
                //jButton1.getActionMap().put("doSomething",anAction);
       // TODO add your handling code here:
    }//GEN-LAST:event_jButton1KeyPressed

    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
    
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(f_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
     //</editor-fold>
     
        //</editor-fold>

        /* Create and display the form */
       
           java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                new f_login().setVisible(true);
                
            }
        });
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jl_eror;
    private javax.swing.JLabel jl_pass;
    private javax.swing.JLabel jlb_name;
    private javax.swing.JTextField jtx_name;
    private javax.swing.JPasswordField jtx_pass;
    // End of variables declaration//GEN-END:variables

private void arror_login ()
{
    jlb_name.setText("");
    jl_pass.setText("");
    jl_eror.setText("");
    
    
    
}
 @SuppressWarnings("deprecation")
    public  boolean test_login () throws SQLException, ClassNotFoundException
{
   
    
    String name =jtx_name.getText();
    @SuppressWarnings("deprecation")
    String pass;
     pass = jtx_pass.getText();
     if(name.equals("") || pass.equals(""))
            {
                if(name.equals(""))
                {
                    jlb_name.setText("ادخل اسم المستخدم");
                    jlb_name.setForeground(Color.red);
                    
                }
                if(pass.equals(""))
                {
                    jl_pass.setText("ادخل كلمه السر");
                    jl_pass.setForeground(Color.red);
                }
                jl_eror.setText("تاكد من اسم المستخدم وكلمه السر*");
                jl_eror.setForeground(Color.red);
                return a;
            }
    
             a= a_login.geta_loginname(name);
            if(a==false)
            {
                jlb_name.setText("اسم الستخدم غير موجود*");
                return a;
            }
          
             a = a_login.getpass(pass);
            if(a == false)
            {
                jl_pass.setText("كلمه السر غير صحيحه*");
                return a;
            }
             a= a_login.getlogin(name, pass);
       if(a==false){
           jl_eror.setText("تاكد من ادخال البيانات بشكل صحيح");
           return a;
       }
       a=true;
       return true;
        
}
}

