/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zsteel;

import    UI.WaitLayerUI;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.event.ActionEvent;


import java.awt.event.ActionListener;
import java.awt.event.ComponentListener;
import java.awt.event.KeyListener;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JLayer;
import javax.swing.JPanel;

import javax.swing.KeyStroke;
import javax.swing.Timer;
import javax.swing.plaf.LayerUI;

/**
 *
 * @author mahmoud
 */


@SuppressWarnings("serial")
public class f_login extends javax.swing.JFrame implements ActionListener, KeyListener, ComponentListener {
 boolean a =false;
      final WaitLayerUI  layerUI = new WaitLayerUI();



    /**
     * Creates new form f_login
     * @throws java.lang.Exception
     */
    public f_login()throws Exception{
        initComponents();
          
        JLayer  <JComponent> jLayer = new JLayer<JComponent>( this.jPanel1, layerUI);
       
          try { 
        new Thread(new Runnable(){
            public void run() { 
                
                EventQueue.invokeLater(new Runnable(){
                    public void run() { 
                        layerUI.stop(); 
                    } 
                }); 
            } 
        }).start();
    } catch (Exception e) {
        e.printStackTrace();
    } 
        add(jLayer);
       
         
    
    

                setIconImage(new ImageIcon(getClass().getResource("/icon/Steel1.png")).getImage());

     

      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jtx_name = new javax.swing.JTextField();
        jtx_pass = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jlb_name = new javax.swing.JLabel();
        jl_pass = new javax.swing.JLabel();
        jl_eror = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("zsteel");
        setBounds(new java.awt.Rectangle(400, 130, 20, 400));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.addComponentListener(this);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtx_name.addActionListener(this);
        jPanel1.add(jtx_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 138, 180, 30));
        jPanel1.add(jtx_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 229, 180, 30));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("تسجيل الدخول");
        jButton1.addActionListener(this);
        jButton1.addKeyListener(this);
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 335, 132, -1));
        jPanel1.add(jlb_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 143, 131, 25));
        jPanel1.add(jl_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 233, 131, 26));
        jPanel1.add(jl_eror, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 479, 150, 21));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(557, 566));
        setLocationRelativeTo(null);
    }

    // Code for dispatching events from components to event handlers.

    public void actionPerformed(java.awt.event.ActionEvent evt) {
        if (evt.getSource() == jtx_name) {
            f_login.this.jtx_nameActionPerformed(evt);
        }
        else if (evt.getSource() == jButton1) {
            f_login.this.jButton1ActionPerformed(evt);
        }
    }

    public void componentHidden(java.awt.event.ComponentEvent evt) {
        if (evt.getSource() == jPanel1) {
            f_login.this.jPanel1ComponentHidden(evt);
        }
    }

    public void componentMoved(java.awt.event.ComponentEvent evt) {
    }

    public void componentResized(java.awt.event.ComponentEvent evt) {
    }

    public void componentShown(java.awt.event.ComponentEvent evt) {
    }

    public void keyPressed(java.awt.event.KeyEvent evt) {
        if (evt.getSource() == jButton1) {
            f_login.this.jButton1KeyPressed(evt);
        }
    }

    public void keyReleased(java.awt.event.KeyEvent evt) {
    }

    public void keyTyped(java.awt.event.KeyEvent evt) {
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
arror_login();
        
 layerUI.start();
         
        try {
            test_login();
            if(a==false){
                return;
            }
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(f_login.class.getName()).log(Level.SEVERE, null, ex);
           
                
        }
         layerUI.start();

        setVisible(false);
        new f_menu().setVisible(true);
        
        // setVisible(false); 
   //  new f_menu().setVisible(true);
     
    
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtx_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtx_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtx_nameActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
                jButton1.getInputMap().put(KeyStroke.getKeyStroke("enter"),"jButton1");
                //jButton1.getActionMap().put("doSomething",anAction);
       // TODO add your handling code here:
    }//GEN-LAST:event_jButton1KeyPressed

    private void jPanel1ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentHidden

        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1ComponentHidden

    /**
     * @param args the command line arguments
     */

 @SuppressWarnings("Convert2Lambda")
    public static void main(String args[]) {
    
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(f_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
     //</editor-fold>
     
        //</editor-fold>

        /* Create and display the form */
       
           java.awt.EventQueue.invokeLater(new Runnable() {
            
            @Override
            public void run() {
                try {
                    new f_login().layerUI.start();
                    
                    new f_login().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(f_login.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        });
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jl_eror;
    private javax.swing.JLabel jl_pass;
    private javax.swing.JLabel jlb_name;
    private javax.swing.JTextField jtx_name;
    private javax.swing.JPasswordField jtx_pass;
    // End of variables declaration//GEN-END:variables

private void arror_login ()
{
    jlb_name.setText("");
    jl_pass.setText("");
    jl_eror.setText("");
    
    
    
}
 @SuppressWarnings("deprecation")
    public  boolean test_login () throws SQLException, ClassNotFoundException
{
   
    
    String name =jtx_name.getText();
    @SuppressWarnings("deprecation")
    String pass;
     pass = jtx_pass.getText();
     if(name.equals("") || pass.equals(""))
            {
                if(name.equals(""))
                {
                    jlb_name.setText("ادخل اسم المستخدم");
                    jlb_name.setForeground(Color.red);
                    
                }
                if(pass.equals(""))
                {
                    jl_pass.setText("ادخل كلمه السر");
                    jl_pass.setForeground(Color.red);
                }
                jl_eror.setText("تاكد من اسم المستخدم وكلمه السر*");
                jl_eror.setForeground(Color.red);
                return a;
            }
    
             a= c_login.geta_loginname(name);
            if(a==false)
            {
                jlb_name.setText("اسم الستخدم غير موجود*");
                return a;
            }
          
             a = c_login.getpass(pass);
            if(a == false)
            {
                jl_pass.setText("كلمه السر غير صحيحه*");
                return a;
            }
             a= c_login.getlogin(name, pass);
       if(a==false){
           jl_eror.setText("تاكد من ادخال البيانات بشكل صحيح");
           return a;
       }
       a=true;
       return true;
        
}
}

