
package zsteel;



import UI.scrollbar;
import UI.tableheader;
import java.awt.Color;
import java.awt.Component;
import java.awt.ComponentOrientation;
import java.awt.Dimension;
import java.awt.Panel;
import javax.swing.ImageIcon;
import javax.swing.JLayer;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import static javax.swing.SwingConstants.RIGHT;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumnModel;



public class f_storo extends javax.swing.JFrame {
       DefaultTableModel m ;
     
     
    boolean address = false ;
    
    
   
    public f_storo() {
        
       
        initComponents();
         address =true ;
        dtable();
       
    selectclient();
       
        setIconImage(new ImageIcon(getClass().getResource("/icon/steel1.png")).getImage());
        setExtendedState(MAXIMIZED_BOTH);
        table.getTableHeader().setDefaultRenderer(new tableheader());
      /* JTableHeader header = table.getTableHeader();
       header.setPreferredSize(new Dimension(0, 30));
       header.setEnabled(false);
       table.getTableHeader().setDefaultRenderer(new tableheader());
    table.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
 table.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
       */
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpgroub = new javax.swing.JPanel();
        jTserech = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrolltable = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jBadd = new javax.swing.JButton();
        jBacountstatment = new javax.swing.JButton();
        jBedit = new javax.swing.JButton();
        jBdelete = new javax.swing.JButton();
        jBexit = new javax.swing.JButton();
        jBmain = new javax.swing.JButton();
        jBprint = new javax.swing.JButton();
        jlb_userlogin = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jBedit1 = new javax.swing.JButton();
        jBedit2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);
        setSize(new java.awt.Dimension(1340, 750));

        jpgroub.setBackground(new java.awt.Color(255, 255, 255));

        jTserech.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTserech.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("zsteel");

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("اداره المخزن");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel10))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(582, 582, 582)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(642, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel4.setText("F+");

        jLabel5.setText("F-");

        jLabel7.setText("H-");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel8.setText("H+");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jScrolltable.getVerticalScrollBar().setUI(new scrollbar());
        jScrolltable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrolltable.setHorizontalScrollBarPolicy(31);
        jScrolltable.setOpaque(false);
        jScrolltable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jScrolltableMouseEntered(evt);
            }
        });

        table.setAutoCreateRowSorter(true);
        table.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        table.setModel(new DefaultTableModel(new Object[0][], new String []{"مسلسل","الصنف","المخزون","اخر سعر شراء","اخر سعر بيع"}));
        table.setRowHeight(30);
        table.setSurrendersFocusOnKeystroke(true);
        jScrolltable.setViewportView(table);

        jBadd.setBackground(new java.awt.Color(250, 250, 250));
        jBadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add1.png"))); // NOI18N
        jBadd.setText("اضافه صنف جديد");
        jBadd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBadd.setContentAreaFilled(false);
        jBadd.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBadd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBadd.setIconTextGap(3);
        jBadd.setInheritsPopupMenu(true);
        jBadd.setOpaque(true);
        jBadd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBadd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBaddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBaddMouseExited(evt);
            }
        });
        jBadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBaddActionPerformed(evt);
            }
        });

        jBacountstatment.setBackground(new java.awt.Color(250, 250, 250));
        jBacountstatment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Overview_50px.png"))); // NOI18N
        jBacountstatment.setText("عرض تفاصيل الصنف");
        jBacountstatment.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBacountstatment.setContentAreaFilled(false);
        jBacountstatment.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBacountstatment.setIconTextGap(3);
        jBacountstatment.setInheritsPopupMenu(true);
        jBacountstatment.setOpaque(true);
        jBacountstatment.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBacountstatment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBacountstatmentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBacountstatmentMouseExited(evt);
            }
        });
        jBacountstatment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBacountstatmentActionPerformed(evt);
            }
        });

        jBedit.setBackground(new java.awt.Color(250, 250, 250));
        jBedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Edit Property_32px.png"))); // NOI18N
        jBedit.setText("تقرير الجرد");
        jBedit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBedit.setContentAreaFilled(false);
        jBedit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBedit.setOpaque(true);
        jBedit.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jBedit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBedit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBeditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBeditMouseExited(evt);
            }
        });

        jBdelete.setBackground(new java.awt.Color(250, 250, 250));
        jBdelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Delete_32px.png"))); // NOI18N
        jBdelete.setText("مسح بيانات الصنف");
        jBdelete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBdelete.setContentAreaFilled(false);
        jBdelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBdelete.setOpaque(true);
        jBdelete.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jBdelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBdelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBdeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBdeleteMouseExited(evt);
            }
        });

        jBexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Exitaa1.jpg"))); // NOI18N
        jBexit.setBorderPainted(false);
        jBexit.setContentAreaFilled(false);
        jBexit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBexit.setFocusPainted(false);
        jBexit.setFocusable(false);
        jBexit.setIconTextGap(0);
        jBexit.setPreferredSize(new java.awt.Dimension(77, 45));
        jBexit.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Delete_32px.png"))); // NOI18N
        jBexit.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Exit_32px.png"))); // NOI18N
        jBexit.setVerifyInputWhenFocusTarget(false);
        jBexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBexitMouseEntered(evt);
            }
        });
        jBexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBexitActionPerformed(evt);
            }
        });

        jBmain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Home1_32px.jpg"))); // NOI18N
        jBmain.setBorderPainted(false);
        jBmain.setContentAreaFilled(false);
        jBmain.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBmain.setFocusPainted(false);
        jBmain.setFocusable(false);
        jBmain.setIconTextGap(0);
        jBmain.setPreferredSize(new java.awt.Dimension(77, 45));
        jBmain.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Delete_32px.png"))); // NOI18N
        jBmain.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Homeblue_32px.png"))); // NOI18N
        jBmain.setVerifyInputWhenFocusTarget(false);
        jBmain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBmainMouseEntered(evt);
            }
        });
        jBmain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmainActionPerformed(evt);
            }
        });

        jBprint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Print11_32px.png"))); // NOI18N
        jBprint.setBorderPainted(false);
        jBprint.setContentAreaFilled(false);
        jBprint.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBprint.setFocusPainted(false);
        jBprint.setFocusable(false);
        jBprint.setIconTextGap(0);
        jBprint.setPreferredSize(new java.awt.Dimension(77, 45));
        jBprint.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Delete_32px.png"))); // NOI18N
        jBprint.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Print1_32px.png"))); // NOI18N
        jBprint.setVerifyInputWhenFocusTarget(false);
        jBprint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBprintMouseEntered(evt);
            }
        });
        jBprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBprintActionPerformed(evt);
            }
        });

        jlb_userlogin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jPanel3.setBackground(new java.awt.Color(0, 102, 255));

        jLabel6.setBackground(new java.awt.Color(51, 102, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("logged in");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6))
        );

        jBedit1.setBackground(new java.awt.Color(250, 250, 250));
        jBedit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Edit Property_32px.png"))); // NOI18N
        jBedit1.setText("تعديل بيانات الصنف");
        jBedit1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBedit1.setContentAreaFilled(false);
        jBedit1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBedit1.setOpaque(true);
        jBedit1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jBedit1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBedit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBedit1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBedit1MouseExited(evt);
            }
        });

        jBedit2.setBackground(new java.awt.Color(250, 250, 250));
        jBedit2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Edit Property_32px.png"))); // NOI18N
        jBedit2.setText("تقرير النواقص");
        jBedit2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBedit2.setContentAreaFilled(false);
        jBedit2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBedit2.setOpaque(true);
        jBedit2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jBedit2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBedit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBedit2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBedit2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jpgroubLayout = new javax.swing.GroupLayout(jpgroub);
        jpgroub.setLayout(jpgroubLayout);
        jpgroubLayout.setHorizontalGroup(
            jpgroubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jpgroubLayout.createSequentialGroup()
                .addGap(930, 930, 930)
                .addComponent(jTserech, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jpgroubLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jScrolltable, javax.swing.GroupLayout.PREFERRED_SIZE, 1220, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jpgroubLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jpgroubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBprint, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBmain, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBexit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(jBedit2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jBedit, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(240, 240, 240)
                .addComponent(jBdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jBedit1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jBacountstatment, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jBadd, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jpgroubLayout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jlb_userlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpgroubLayout.setVerticalGroup(
            jpgroubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpgroubLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jTserech, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jpgroubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrolltable, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jpgroubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpgroubLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jBprint, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jBmain, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jBexit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBedit2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBedit, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpgroubLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jBdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpgroubLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jBedit1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpgroubLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jBacountstatment, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpgroubLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jBadd, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3)
                .addGroup(jpgroubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlb_userlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpgroub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpgroub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBaddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBaddMouseEntered
  jBadd.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jBaddMouseEntered

    private void jBaddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBaddMouseExited
      jBadd.setBackground(Color.white);
    }//GEN-LAST:event_jBaddMouseExited

    private void jBaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBaddActionPerformed
        new D_addclient(this, address).setVisible(true);
     //   JLayer<Component> blurLayer = new JLayer<Component>(this.getContentPane(), new BlurLayerUI());
//setContentPane(blurLayer);
        System.out.println("zsteel.f_custmor.jBaddActionPerformed()");
    }//GEN-LAST:event_jBaddActionPerformed

    private void jBacountstatmentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBacountstatmentMouseEntered
       jBacountstatment.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jBacountstatmentMouseEntered

    private void jBacountstatmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBacountstatmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBacountstatmentActionPerformed

    private void jBacountstatmentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBacountstatmentMouseExited

        jBacountstatment.setBackground(Color.WHITE);
    }//GEN-LAST:event_jBacountstatmentMouseExited

    private void jBeditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBeditMouseEntered
        jBedit.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jBeditMouseEntered

    private void jBeditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBeditMouseExited
        jBedit.setBackground(Color.WHITE);
    }//GEN-LAST:event_jBeditMouseExited

    private void jBdeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBdeleteMouseEntered
        jBdelete.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jBdeleteMouseEntered

    private void jBdeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBdeleteMouseExited
        jBdelete.setBackground(Color.white);
    }//GEN-LAST:event_jBdeleteMouseExited

    private void jBexitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBexitMouseEntered
        jBexit.setBackground(Color.red);
        // TODO add your handling code here:
    }//GEN-LAST:event_jBexitMouseEntered

    private void jBexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBexitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBexitActionPerformed

    private void jBmainMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBmainMouseEntered
        jBexit.setBackground(Color.red);
        // TODO add your handling code here:
    }//GEN-LAST:event_jBmainMouseEntered

    private void jBmainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBmainActionPerformed

    private void jBprintMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBprintMouseEntered
        jBexit.setBackground(Color.red);
        // TODO add your handling code here:
    }//GEN-LAST:event_jBprintMouseEntered

    private void jBprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBprintActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBprintActionPerformed

    private void jScrolltableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrolltableMouseEntered
        jScrolltable.getVerticalScrollBar().setForeground(Color.red);
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrolltableMouseEntered

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
 table.setRowHeight(table.getRowHeight()+1);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        table.setRowHeight(table.getRowHeight()-1);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jBedit1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBedit1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jBedit1MouseEntered

    private void jBedit1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBedit1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jBedit1MouseExited

    private void jBedit2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBedit2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jBedit2MouseEntered

    private void jBedit2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBedit2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jBedit2MouseExited
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(f_storo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(f_storo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(f_storo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(f_storo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new f_storo().setVisible(true);
            }
        });
    }
  

    public  void dtable ()
    {
        String [] columnx = {"مسلسل","الصنف","المخزون","اخر سعر شراء","اخر سعر بيع"};
     //  String []columnz = {"مسلسل","نوع المتعامل","الاسم","دائن","مدين","اخر دفعه","تاريخ اخر تحديث"}; 
        
       
       m = new DefaultTableModel(columnx,0)
       {
            Class[] types = { Integer.class, String.class, String.class, String.class, String.class, String.class };
        
            public boolean iscelleditable(int row , int column)
         {
             return true;
         }
        
         
       };
       table.setModel(m);
        
        
        
          
           
           
        
        table.setModel(m);
        Object []a={"1","سيليبليبل","sdf","sfd","fsd","fds","dfs"};       
        
        m.addRow(a);
      
        
      
    
     
        
          JTableHeader header = table.getTableHeader();
       header.setPreferredSize(new Dimension(0, 30));
       header.setEnabled(false);
       table.getTableHeader().setDefaultRenderer(new tableheader());
    table.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);

       
        jScrolltable.getViewport().setBackground(Color.white);
        Panel p =new Panel();
        p.setBackground(Color.BLACK);
        jScrolltable.setCorner("UPPER_RIGHT_CORNER", p);
        jScrolltable. setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        table.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        
        
   
        
        
        
        //start customize  size column range 60:200
        TableColumnModel column = table.getColumnModel();
        
       /* if(address){
        column.getColumn(0).setPreferredWidth(60);
        column.getColumn(0).setMaxWidth(60);
        column.getColumn(1).setPreferredWidth(100);
        column.getColumn(1).setMaxWidth(100);
        column.getColumn(2).setPreferredWidth(150);
        column.getColumn(2).setMaxWidth(150);
        column.getColumn(3).setPreferredWidth(150);
        column.getColumn(3).setMaxWidth(150);
        column.getColumn(4).setPreferredWidth(150);
        column.getColumn(4).setMaxWidth(150);
        column.getColumn(5).setPreferredWidth(150);
        column.getColumn(5).setMaxWidth(150);
        column.getColumn(6).setPreferredWidth(150);
        column.getColumn(6).setMaxWidth(150);
//        column.getColumn(7).setPreferredWidth(150);
  //      column.getColumn(7).setMaxWidth(150);
       // column.getColumn(8).setPreferredWidth(150);
       // column.getColumn(8).setMaxWidth(150);
        }
        else 
        {
            address= false;
            
        }
        table.setColumnModel(column);
        //end size column
        */
      
        table.setDefaultEditor(Object.class, null);
        
        //start customize row in table
       /* DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(0);
    table.getColumnModel().getColumn(0).setCellRenderer(rightRenderer);    
    table.getColumnModel().getColumn(1).setCellRenderer(rightRenderer);
    table.getColumnModel().getColumn(2).setCellRenderer(rightRenderer);
    table.getColumnModel().getColumn(3).setCellRenderer(rightRenderer);
    table.getColumnModel().getColumn(4).setCellRenderer(rightRenderer);
    table.getColumnModel().getColumn(5).setCellRenderer(rightRenderer);
    table.getColumnModel().getColumn(6).setCellRenderer(rightRenderer);
    table.getColumnModel().getColumn(7).setCellRenderer(rightRenderer);
    table.getColumnModel().getColumn(8).setCellRenderer(rightRenderer);
  // end customize row
  */
       DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
     
        
        
      
    
    renderer.setHorizontalAlignment(RIGHT);
    for (int i = 0; i < table.getColumnCount(); i++)
    {
      table.getColumn(table.getColumnName(i)).setCellRenderer(renderer);

    }
       
        
        table.setModel(m);
       
    }
    private void selectclient()
    {
   
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBacountstatment;
    private javax.swing.JButton jBadd;
    private javax.swing.JButton jBdelete;
    private javax.swing.JButton jBedit;
    private javax.swing.JButton jBedit1;
    private javax.swing.JButton jBedit2;
    private javax.swing.JButton jBexit;
    private javax.swing.JButton jBmain;
    private javax.swing.JButton jBprint;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrolltable;
    private javax.swing.JTextField jTserech;
    public javax.swing.JLabel jlb_userlogin;
    private javax.swing.JPanel jpgroub;
    public javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
